/**
 * 统计查询--方案相关常量
 */
define(function(require) {
	var scheme = {
			//统计项目-对象范围
			items:[
			    {
			    	value:'person',
			    	label:'检查人'
			    },
			    {
			    	value:'equip',
			    	label:'区域 / 设施'
			    },
			    {
			    	value:'checkItem',
			    	label:'检查项',
			    	children:[
						{value:'1',label:'不合格项'},
						{value:'2',label:'合格率'}
			    	]
			    },
			    {
			    	value:'rectification',
			    	label:'整改情况',
			    	children:[
						{value:'1',label:'整改率'},
				        {value:'2',label:'超期未整改'}
			    	]
			    },
			    {
			    	value:'taskPlan',
			    	label:'计划任务',
			    	children:[
						{
							value:'1',
							label:'实际执行'
						},
				        {
							value:'2',
							label:'超期执行'
						}
			    	]
			    }
			],
			typeOfRanges:{
				"0":[
					{value:"frw",label:'公司'},
				 	{value:"dep",label:'部门'}
				],
				"1":[
				     {value:"frw",label:'公司'},
				     {value:"dep",label:'部门'},
				     {value:"per",label:'人员'}
				],
				"2":[
					{value:"frw",label:'公司'},
					{value:"dep",label:'部门'},
					//{value:"obj",label:'受检对象'},
					{value:"equip",label:'设备设施'}
				]
			},
			urlOfRange:{
				frw:'organization/list',//公司
				dep:'organization/list',//部门
				per:'organization/list',//人员
				obj:'organization/list'//受检对象
			},
			//项目指标
			indicators:{
				checkItem:[
						{value:'1',label:'不合格项'},
						{value:'2',label:'合格率'}
				],
				rectification:[
				         {value:'1',label:'整改率'},
				         {value:'2',label:'超期未整改'}
				]
			},
			//数据来源
			sourceInfos:[
				{value:'0',label:'全部'},
				{value:'1',label:'抽检'}
			]
	};
	return scheme;
});